import { StyleSheet } from 'react-native';
import { appTheme } from '../../theme/appTheme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: appTheme.colors.pageBg, paddingHorizontal: 16 },
  topBar: { marginBottom: 4 },
  title: { fontSize: 24, fontWeight: '800', color: appTheme.colors.textPrimary, marginBottom: 6 },
  subtitle: { fontSize: 14, color: appTheme.colors.textSecondary, marginBottom: 16, lineHeight: 20 },
  card: {
    backgroundColor: appTheme.colors.cardBg,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: appTheme.colors.cardBorder,
    padding: 14,
    marginBottom: 10,
    shadowColor: '#6D5DFB',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  cardPressable: {
    borderColor: '#D8CBFF',
  },
  headerRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 14 },
  headerTextWrap: { flex: 1, marginRight: 10 },
  orderBadge: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#EEE7FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  orderBadgeText: { fontSize: 14, fontWeight: '800', color: appTheme.colors.primaryDark },
  exerciseName: { fontSize: 16, fontWeight: '700', color: appTheme.colors.textPrimary, marginBottom: 3 },
  exerciseMeta: { fontSize: 12, color: appTheme.colors.textSecondary },
  intensityPill: {
    backgroundColor: '#ECE9FF',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  intensityPillText: { fontSize: 12, color: appTheme.colors.primaryDark, fontWeight: '700' },
  statsRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  statCard: {
    flex: 1,
    backgroundColor: '#F8F5FF',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#E9DFFF',
  },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  label: { fontSize: 12, color: appTheme.colors.textSecondary, marginBottom: 4 },
  value: { fontSize: 13, color: appTheme.colors.textPrimary, fontWeight: '700' },
  linkText: { fontSize: 13, color: appTheme.colors.primaryDark, fontWeight: '700' },
  notes: { marginTop: 10, fontSize: 13, color: '#334155', lineHeight: 20 },
  emptyText: {
    fontSize: 14,
    color: appTheme.colors.textSecondary,
    backgroundColor: appTheme.colors.cardBg,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: appTheme.colors.cardBorder,
  },
});
